name: B2V Marketing
tagline: Connect with us on
baseurl: "" # the subpath of your site, e.g. /blog
url: "b2vmarketing.com" # the base hostname & protocol for your site, e.g. http://example.com

# Brand image
Image_URL: 

# Background image
Cover_Image: 

links:

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: b2vmarketing
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/company
    Username: b2vmarketing
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

    # TIKTOK
  - Name: TikTok
    URL: https://www.tiktok.com
    Username: '@b2v.marketing'
    Color: '#FE2C55'
    Icon-Class: fab fa-tiktok

  #  # YOUTUBE
  #- Name: YouTube
  #  URL: https://www.youtube.com/channel
  #  Username: 
  #  Color: '#ff0000'
  #  Icon-Class: fab fa-youtube

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

compress_html:
  clippings: all

footer: 'Yes'

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon